matrix:
  fast_finish: true
  include:
  - os: linux
    services: docker
    language: python
    env:
    - TRAVIS_CONFIG=linux
    - DOCKER_COMPOSE=${TRAVIS_BUILD_DIR}/.docker/docker-compose.travis.yml
    - DOCKER_TAG=$(if [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]]; then if [[ $TRAVIS_EVENT_TYPE
      =~ push ]]; then echo $TRAVIS_BRANCH | sed 's/master/latest/'; elif [[ $TRAVIS_EVENT_TYPE
      =~ pull_request ]] && [[ `git log --format=%B --no-merges -n 1` =~ \[dockerdeps\]
      ]]; then echo "PR-$TRAVIS_PULL_REQUEST"; else echo "latest"; fi; else echo "latest";
      fi)
    - DOCKER_DEPS_PUSH=$(if [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && [[ $TRAVIS_EVENT_TYPE
      =~ push ]] || [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && [[ $TRAVIS_EVENT_TYPE
      =~ pull_request ]] && [[ `git log --format=%B --no-merges -n 1` =~ \[dockerdeps\]
      ]]; then echo "true"; else echo "false"; fi )
    - DOCKER_DEPS_IMAGE_REBUILD=$( [[ $TRAVIS_COMMIT_MESSAGE =~ '[docker] update dependencies'
      ]] && echo "true" || echo "false" )
    - DOCKER_QGIS_IMAGE_BUILD_PUSH=$( [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && [[ $TRAVIS_EVENT_TYPE
      =~ cron ]] && echo "true" || echo "false" )
    - QGIS_LAST_BUILD_SUCCESS=true
    - TRAVIS_TIMESTAMP=$(date +%s)
    - CCACHE_DIR=${HOME}/.ccache
    dist: trusty
    sudo: false
    cache:
      apt: true
      pip: true
      directories:
      - "$HOME/.ccache"
      timeout: 1000
    compiler: clang
    python: '3.5'
    addons:
      apt:
        sources:
        packages:
  - os: linux
    language: python
    python: '3.5'
    env:
    - TRAVIS_CONFIG=code_layout
    dist: trusty
    sudo: false
    cache:
      apt: true
    addons:
      apt:
        sources:
        - sourceline: ppa:jonathonf/backports
        - sourceline: ppa:sergey-dryabzhinsky/packages
        packages:
        - doxygen
        - graphviz
        - txt2tags
        - pkg-config
        - xvfb
        - flip
        - perl
        - silversearcher-ag
        - expect-dev
        - coreutils
        - libyaml-tiny-perl
git:
  depth: 120
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/467e3aff72e344d1dae3
    on_success: change
    on_failure: always
    on_start: never
before_install:
- "./.ci/travis/${TRAVIS_CONFIG}/before_install.sh"
install:
- "./.ci/travis/${TRAVIS_CONFIG}/install.sh"
before_script:
- "./.ci/travis/${TRAVIS_CONFIG}/before_script.sh"
script:
- "./.ci/travis/${TRAVIS_CONFIG}/script.sh"
after_script:
- "./.ci/travis/${TRAVIS_CONFIG}/after_script.sh"
env:
  global:
  # docker usr & pwd
  - secure: Cg2F2wKuh8q4dAPZW/vXHhNUMsvwAlNGTYQSXmiuGiHupYZ4rkOPagal9HGFKcp09Fpjus/yGmIh9HqNeOQB498xIbqbfCDvD57haFwXXOWE259WRgu6jE41+B2jLuyjUog3dbHoUwLOMmdkm1qI4EOTekyAFv9fhHfkFMNSlFA=
  - secure: CvQJKEvzm8d7YBUoK9CjDdRkNKFBxs4U4k4q0m7yMg2NnUNgZh1rA26BDwFQJWFODiWNeYMlw6WlPfMiLi8rBTPZodtzapiasExbLc7jX7tHKkuEJsQBC4pcZfQ8FbPZxhR4W42Aj36nfqmE+QBZA2BPwAVmrF3buFN3j0oDzUM=
